# Generated by Django 5.1.7 on 2025-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='crosses_antimeridian',
            field=models.BooleanField(default=False),
        ),
    ]
