# Generated by Django 5.1.7 on 2025-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0002_invalidpolygon_polygonuserassignment_polygon_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidpolygon',
            name='crosses_antimeridian',
            field=models.BooleanField(default=False),
        ),
    ]
